# Generated by Django 3.0.8 on 2021-02-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ekongaa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True)),
                ('img_link', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='jumiaa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kimg_link', models.URLField(blank=True)),
                ('ktitle', models.CharField(blank=True, max_length=300)),
                ('kprice', models.IntegerField(blank=True, default=0)),
                ('klink', models.URLField(blank=True)),
                ('img_link', models.URLField(blank=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
