# Generated by Django 3.0.8 on 2021-02-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumiaa',
            name='kprice',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='jumiaa',
            name='price',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
