# Generated by Django 3.0.8 on 2021-02-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210205_1634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ekongaa',
        ),
    ]
