# Generated by Django 3.0.8 on 2021-03-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_ekongaa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jumiaa',
            old_name='img_link',
            new_name='ekonga_img_link',
        ),
        migrations.RenameField(
            model_name='jumiaa',
            old_name='kimg_link',
            new_name='ekonga_product_link',
        ),
        migrations.RenameField(
            model_name='jumiaa',
            old_name='kprice',
            new_name='ekonga_product_price',
        ),
        migrations.RenameField(
            model_name='jumiaa',
            old_name='ktitle',
            new_name='ekonga_product_title',
        ),
        migrations.RenameField(
            model_name='jumiaa',
            old_name='klink',
            new_name='jumia_img_link',
        ),
        migrations.RenameField(
            model_name='jumiaa',
            old_name='price',
            new_name='jumia_price',
        ),
        migrations.RenameField(
            model_name='jumiaa',
            old_name='title',
            new_name='jumia_product_title',
        ),
    ]
