# Generated by Django 3.0.8 on 2021-04-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210329_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=300)),
                ('password', models.CharField(blank=True, max_length=300)),
                ('email', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
